package com.thy.casestudy.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class Employee {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //Means that the primary key will be generated by the database, typically using an auto-increment column.
    private Long id;

    @Column(nullable = false)
    @NotBlank(message = "Name is mandatory")
    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    //Many "employees" can belong to one "department".
    //Fetch type lazy means the related entity is not loaded immediately. Instead, it’s loaded on demand (employee.getDepartment();)
    @JoinColumn(name = "department_id")
    //Foreign key column; The foreign key column (department_id) refers to the primary key (id) in the Department table.
    @JsonBackReference  // Breaks the recursion from Employee -> Department
    private Department department;

}

